# AWS ECS Task Definition for Alleviate Health API
# This file can be used with AWS CLI or CloudFormation

apiVersion: v1
kind: Service
metadata:
  name: alleviate-health-api
  labels:
    app: alleviate-health-api
spec:
  selector:
    app: alleviate-health-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alleviate-health-api
  labels:
    app: alleviate-health-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alleviate-health-api
  template:
    metadata:
      labels:
        app: alleviate-health-api
    spec:
      containers:
      - name: alleviate-health-api
        image: your-account.dkr.ecr.region.amazonaws.com/alleviate-health-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
